spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://192.168.101.30:5432/batch_test
#      url: jdbc:postgresql://192.168.27.30:5432/batch_test
      username: postgres
      password: cafebabe
task:
  cron:
    person: 0 0 *  * * ?